In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [4]:
obj=Series([1,10,8,521,0,-9])

In [5]:
obj

0      1
1     10
2      8
3    521
4      0
5     -9
dtype: int64

In [6]:
obj[2]

8

In [10]:
obj.values

array([  1,  10,   8, 521,   0,  -9])

In [11]:
obj.index
Int64Index([0, 1, 2, 3])

IndentationError: unexpected indent (1677773566.py, line 2)

In [14]:
obj.index


RangeIndex(start=0, stop=6, step=1)

In [17]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)

d    4
b    7
a   -5
c    3
dtype: int64


In [18]:
obj[0]

1

In [22]:
obj2['a']=6

In [23]:
obj2

d    4
b    7
a    6
c    3
dtype: int64

In [25]:
obj[:2]

0     1
1    10
dtype: int64

In [26]:
obj2 * 2

d     8
b    14
a    12
c     6
dtype: int64

In [29]:
'p' in obj2

False

In [31]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [32]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [33]:
obj3 = Series(sdata)

In [34]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [35]:
1 in obj

True

In [36]:
10 in obj

False

In [37]:
obj3.values

array([35000, 71000, 16000,  5000])

In [38]:
obj3.keys

<bound method Series.keys of Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64>

In [40]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [41]:
states

['California', 'Ohio', 'Oregon', 'Texas']

In [42]:
obj4=Series(states)

In [43]:
obj4

0    California
1          Ohio
2        Oregon
3         Texas
dtype: object

In [44]:
pd.isnull(obj4)

0    False
1    False
2    False
3    False
dtype: bool

In [45]:
obj2+obj

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

In [46]:
obj3+obj4

0         NaN
1         NaN
2         NaN
3         NaN
Ohio      NaN
Oregon    NaN
Texas     NaN
Utah      NaN
dtype: object

In [47]:
obj4

0    California
1          Ohio
2        Oregon
3         Texas
dtype: object

In [48]:
obj4.name='population'

In [50]:
{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [51]:
states

['California', 'Ohio', 'Oregon', 'Texas']

In [52]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [53]:
states

['California', 'Ohio', 'Oregon', 'Texas']

In [55]:
obj4 = Series(sdata, index=states)

In [58]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [59]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [60]:
obj.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [62]:
obj.notnull()

0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool

In [63]:
obj[0]=0

In [64]:
obj.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [65]:
obj

0      0
1     10
2      8
3    521
4      0
5     -9
dtype: int64

In [66]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [67]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [69]:
frame = DataFrame(data)

In [70]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

ModuleNotFoundError: No module named 'pd'

In [74]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],

index=['one', 'two', 'three', 'four', 'five'])

In [76]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [77]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [78]:
obj4.name='polpulation'

In [79]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: polpulation, dtype: float64

In [81]:
date=DataFrame(obj4)

In [82]:
date

polpulation
California          NaN
Ohio            35000.0
Oregon          16000.0
Texas           71000.0

In [83]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [84]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],

index=['one', 'two', 'three', 'four', 'five'])

In [85]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [86]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [87]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [89]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],

index=['one', 'two', 'three', 'four', 'five'])

In [90]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [92]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [94]:
frame2.ix['two']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [95]:
frame2['debt'] = 16.5

In [96]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [97]:
frame2['debt'][:3] = 1

/tmp/ipykernel_4974/3853371814.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame2['debt'][:3] = 1


In [98]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   1.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   1.0
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [101]:
frame2['debt'] = np.arange(5)

NameError: name 'np' is not defined

In [102]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [103]:
frame2['debt'] = val

In [104]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [105]:
frame2['new'] = val

In [106]:
frame2

year   state  pop  debt  new
one    2000    Ohio  1.5   NaN  NaN
two    2001    Ohio  1.7  -1.2 -1.2
three  2002    Ohio  3.6   NaN  NaN
four   2001  Nevada  2.4  -1.5 -1.5
five   2002  Nevada  2.9  -1.7 -1.7

In [108]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'new'], dtype='object')

In [109]:
del frame2['debt']

In [111]:
frame2

year   state  pop  new
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7 -1.2
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4 -1.5
five   2002  Nevada  2.9 -1.7

In [113]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},

 'Ohio':{2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [114]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [115]:
frame3=DataFrame(pop)

In [116]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [117]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [118]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [119]:
frame3.T.values

array([[2.4, 2.9, nan],
       [1.7, 3.6, 1.5]])

In [121]:
pdata = {'Ohio': frame3['Ohio'][:-1],
frame3['Nevada'][:2]}


SyntaxError: invalid syntax (3898391901.py, line 2)

In [122]:
pdata = {'Ohio': frame3['Ohio'][:-1],

'Nevada': frame3['Nevada'][:2]}

In [123]:
pdata

{'Ohio': 2001    1.7
 2002    3.6
 Name: Ohio, dtype: float64,
 'Nevada': 2001    2.4
 2002    2.9
 Name: Nevada, dtype: float64}

In [124]:
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [126]:
frame3

Nevada  Ohio
year              
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [133]:
frame3.columns.name = 't'

In [134]:
frame3

t     Nevada  Ohio
year              
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [135]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [136]:
obj

0      0
1     10
2      8
3    521
4      0
5     -9
dtype: int64

In [137]:
obj.index

RangeIndex(start=0, stop=6, step=1)

In [138]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [139]:
obj

a    0
b    1
c    2
dtype: int64

In [140]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [141]:
obj2 = Series([1.5, -2.5, 0], index=index)

NameError: name 'index' is not defined

In [142]:
index = pd.Index(np.arange(3))

NameError: name 'np' is not defined

In [143]:
obj2 = Series([1.5, -2.5, 0], index=index)

NameError: name 'index' is not defined