In [3]:
import numpy as np


In [4]:
print(np.__version__)

1.22.4


In [6]:
arr=[12.23, 13.32, 100, 36.32]
nupy=np.array(arr)
print(nupy)

[ 12.23  13.32 100.    36.32]


In [13]:
matrix=np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
matrix=np.array(np.arange(1,10)).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
vector=np.array(np.zeros(10))
print(vector)
vector[5]=11
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [18]:
arr=np.array(np.arange(12,68))
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
 60 61 62 63 64 65 66 67]


In [19]:
print(arr[::-1])

[67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44
 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20
 19 18 17 16 15 14 13 12]


In [20]:
print(arr[::-2])

[67 65 63 61 59 57 55 53 51 49 47 45 43 41 39 37 35 33 31 29 27 25 23 21
 19 17 15 13]


In [21]:
print(arr[::-5])

[67 62 57 52 47 42 37 32 27 22 17 12]


In [34]:
convert=np.array([1, 2, 3, 4],dtype='f8')
print(convert.dtype)


float64


In [68]:
t=np.array(np.zeros(16)).reshape(4,4)
t[1:-1,1:-1]=1

print(t)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


 t=np.ones((3,3))
t = np.pad(t, pad_width=1, mode='constant', constant_values=0)
print(t)

In [85]:
t=np.ones((4,4))
t=np.pad(t,pad_width=1,mode='constant',constant_values=0)
print(t)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [84]:
x = np.ones((3,2))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [95]:
t=np.ones((4,4))
t=np.pad(t,pad_width=2,mode='constant',constant_values=0)
print(t)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [100]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [101]:
np.pad?

In [102]:
2*2

4

2# Bonjour

## BONJOUR

In [104]:
2# BONJOUR

2

<b>BONJOUR</b>

<font color="red">VOILA</font>

In [1]:
import numpy as np


In [3]:
x = np.arange(1, 8, 3)
z = x.reshape(3, 1)
print(z)

[[1]
 [4]
 [7]]


In [4]:
x = np.arange(1, 5)
x = x*2

In [5]:
print(x)

[2 4 6 8]


In [7]:
print(x[:3].sum())



12


In [16]:
import numpy as np

data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])

moy=data.mean()
som=0


for i in data:
    som+=int(i)**2

ecart=((som/len(data)-moy**2)**0.5

for i in data:
    count=0
    prcnt=0
    for j in data:
        if int(i)==int(j):
            count+=1
        prcnt=(count/len(data))*100

    if moy-ecart<=prcnt<=moy+ecart:
        print(prcnt)


SyntaxError: invalid syntax (1365023280.py, line 14)

In [20]:
import pandas as pd

df = pd.read_csv("/usercode/files/ca-covid.csv")

df.drop('state', axis=1, inplace=True)
df.set_index('date', inplace=True)
df=pd.DataFrame(df)
df['ratio']=df['deaths']/df['cases']
print(df.groupby('day').max())

FileNotFoundError: [Errno 2] No such file or directory: '/usercode/files/ca-covid.csv'

In [1]:
import numpy as np

data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])


In [2]:
import numpy as np

In [8]:
data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])


In [9]:
print(data)

[150000 125000 320000 540000 200000 120000 160000 230000 280000 290000
 300000 500000 420000 100000 150000 280000]


In [10]:
dlist=list(data)

In [11]:
print(dlist)

[150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000]


In [13]:
print(sum(dlist))

4165000


In [23]:
import numpy as np

data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])

dlist=list(data)
moy=sum(dlist)/len(dlist)
somM=0

for i in dlist:
    somM+=int(i)**2

variance=((somM/len(dlist))-(moy**2))
ecart=variance**0.5

#Pourcentages
for i in dlist:
    compt=0
    for j in dlist:
        if int(j)==int(i):
            compt+=1
    pourcent=(compt/len(dlist))*100
    #print(f'POurcent : {pourcent} Moyenne-ecrat : {moy-ecart} Moyenne+ecart : {moy+ecart}')
    if moy-ecart<= pourcent<=moy+ecart:
        print(f' Pourcentages valide : {pourcent}')

In [24]:
import numpy as np

data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])

dlist=list(data)
moy=sum(dlist)/len(dlist)
somM=0

for i in dlist:
    somM+=int(i)**2

variance=((somM/len(dlist))-(moy**2))
ecart=variance**0.5

#Pourcentages
for i in dlist:
    compt=0
    for j in dlist:
        if int(j)==int(i):
            compt+=1
    pourcent=(compt/len(dlist))*100
    if moy-ecart<=int(i)<=moy+ecart:
        print(pourcent)

12.5
6.25
6.25
6.25
6.25
12.5
6.25
6.25
12.5
12.5
